name: Deploy Django App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      CONTAINER_MODE: ${{ secrets.CONTAINER_MODE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy containers (Linux or Windows)
        shell: bash
        run: |
          if [ "$CONTAINER_MODE" = "windows" ]; then
            docker-compose -f docker-compose.windows.yml --env-file env.windows up -d --build
          else
            docker-compose -f docker-compose.linux.yml --env-file env.linux up -d --build
          fi

      - name: Stop and remove old containers
        run: |
          docker-compose down || true 